# Configuration file for Automation IA

# General settings
app:
  name: "Automation IA"
  version: "1.0.0"
  debug: true

# AI/ML settings
ai:
  model: "gpt-3.5-turbo"
  max_tokens: 1000
  temperature: 0.7

# Automation settings
automation:
  enabled: true
  schedule: "0 9 * * *"  # Daily at 9 AM
  max_retries: 3
  timeout: 30

# Logging
logging:
  level: "INFO"
  file: "logs/automation.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Data settings
data:
  input_dir: "data/input"
  output_dir: "data/output"
  backup_dir: "data/backup"
